FROM python:3.9

WORKDIR /app

RUN mkdir -p /app/lib

COPY ../lib /app
COPY ../api /app
COPY qa_lab_api.sh /app

RUN pip install --no-cache-dir -r pip_requirements.txt

# Command to run the API
CMD ["uvicorn", "unittestapi:app", "--host", "0.0.0.0", "--port", "8000"]
